### ISSUE TITLE
VFuncSwap doesn't work on x64?

### ISSUE THREAD

**Issue by zezba9000** [stevemk14ebr/PolyHook#23] opened 2017-04-14 22:05 UTC
So am trying to hook a Virtual method but its not work on 64 builds.
**I get an exception when trying to delete the "delete shimTrackedDevice;"**
**Also the "thisptr" is invalid**
My system is Win10 x64, Visual Studio 2017.

referencing: https://www.codeproject.com/articles/1100579/polyhook-the-cplusplus-x-x-hooking-library

```
// ----------------------------------------------------------
// hooks
// ----------------------------------------------------------
void** trackedDeviceVTable = nullptr;
constexpr int trackedDeviceVTableIndex_GetPose_Index = 5;
typedef DriverPose_t(__thiscall *GetPose_Org)(ITrackedDeviceServerDriver* thisptr);
GetPose_Org GetPose_Ptr = nullptr;

float x = 0;
ITrackedDeviceServerDriver* thisptr__ = nullptr;
static DriverPose_t __fastcall GetPose_Hook(ITrackedDeviceServerDriver* thisptr)//, int edx)
{
	if (thisptr__ == thisptr) cout << "Valid This Ptr!!!" << endl;
	else cout << "Invalid This Ptr!!!" << endl;
	return GetPose_Ptr(thisptr);
}

PLH::VFuncSwap* VFuncSwap_Ex = new PLH::VFuncSwap;
void HookDriver(ITrackedDeviceServerDriver* driver, bool usePolyHook)
{
	thisptr__ = driver;

	if (usePolyHook)
	{
		VFuncSwap_Ex->SetupHook(*(BYTE***)driver, trackedDeviceVTableIndex_GetPose_Index, (BYTE*)&GetPose_Hook);
		VFuncSwap_Ex->Hook();
		GetPose_Ptr = VFuncSwap_Ex->GetOriginal<GetPose_Org>();
	}
	else
	{
		trackedDeviceVTable = *(void***)(driver);
		#ifdef _32BIT
		MEMORY_BASIC_INFORMATION32 trackedDeviceMBI;
		VirtualQuery((LPCVOID)trackedDeviceVTable, (PMEMORY_BASIC_INFORMATION)&trackedDeviceMBI, sizeof(MEMORY_BASIC_INFORMATION32));
		#else
		MEMORY_BASIC_INFORMATION64 trackedDeviceMBI;
		VirtualQuery((LPCVOID)trackedDeviceVTable, (PMEMORY_BASIC_INFORMATION)&trackedDeviceMBI, sizeof(MEMORY_BASIC_INFORMATION64));
		#endif
		VirtualProtect((LPVOID)trackedDeviceMBI.BaseAddress, trackedDeviceMBI.RegionSize, PAGE_EXECUTE_READWRITE, &trackedDeviceMBI.Protect);// unlock
		GetPose_Ptr = (GetPose_Org)trackedDeviceVTable[trackedDeviceVTableIndex_GetPose_Index];
		trackedDeviceVTable[trackedDeviceVTableIndex_GetPose_Index] = &GetPose_Hook;// Hook!
		VirtualProtect((LPVOID)trackedDeviceMBI.BaseAddress, trackedDeviceMBI.RegionSize, trackedDeviceMBI.Protect, &trackedDeviceMBI.Protect);// lock
	}
}

static ShimTrackedDevice* shimTrackedDevice = new ShimTrackedDevice();
int main()
{
	cout << "Call before hook..." << endl;
	auto result = shimTrackedDevice->GetPose();

	cout << "Hooking..." << endl;
	HookDriver(shimTrackedDevice, true);

	cout << "Calling Hooked..." << endl;
	result = shimTrackedDevice->GetPose();

	cout << "Deleting..." << endl;
	delete shimTrackedDevice;
	shimTrackedDevice = nullptr;

	cout << "Finished!" << endl;
    return 0;
}
```

**Comment by zezba9000** [comment] 2017-04-14 22:07
Download link to none working proj: https://www.dropbox.com/s/2pdrtpfg41u09zs/HookTest.7z?dl=0

**Comment by zezba9000** [comment] 2017-04-14 22:10
Return value looks like:
```
struct DriverPose_t
{
	double poseTimeOffset;
	HmdQuaternion_t qWorldFromDriverRotation;
	double vecWorldFromDriverTranslation[3];
	HmdQuaternion_t qDriverFromHeadRotation;
	double vecDriverFromHeadTranslation[3];
	double vecPosition[3];
	double vecVelocity[3];
	double vecAcceleration[3];
	HmdQuaternion_t qRotation;
	double vecAngularVelocity[3];
	double vecAngularAcceleration[3];
	ETrackingResult result;
	bool poseIsValid;
	bool willDriftInYaw;
	bool shouldApplyHeadModel;
	bool deviceIsConnected;
};
```

**Comment by stevemk14ebr** [comment] 2017-04-14 22:25
assuming you have the correct vtable and your own implementation of the vtable hook works then i don't know why it fails. Look at my code the implementations are identical. You will have to debug yourself, i cannot debug your target. Define doesn't work, fails to hook or what?

**Comment by zezba9000** [comment] 2017-04-14 23:54
> your own implementation of the vtable hook works

-- It doesn't on x64 but does on x86. Its why I'm trying to use PolyHook. x64 isn't hooking correctly.


So to be more clear hooking a method that returns the "DriverPose_t" on x64 doesn't work correctly...

**What does work on x86 (32 bit)** [in short everything works]:
 * PolyHook: Fully hooks and works just fine.
 * My VirtualProtect Implementation: Fully hooks and works just fine.

**What doesn't work on x64 (64 bit)** [in short partially works]:
 * PolyHook: Hooks but the "this ptr" passed into the GetPose_Hook is wrong.
 * My VirtualProtect Implementation: Hooks but the "this ptr" passed into the GetPose_Hook is wrong.

So on x64 the hooked "GetPose_Hook" gets called. However the "ITrackedDeviceServerDriver* thisptr" value is invalid.

I have also tried to hook with the "VFuncDetour" object and have the same issue.
```
VFuncDetour_Ex->SetupHook(*(BYTE***)driver, 5, (BYTE*)&GetPose_Hook); //can cast to byte* to
VFuncDetour_Ex->Hook();
GetPose_Ptr = VFuncDetour_Ex->GetOriginal<GetPose_Org>();
```

FYI: with the "VFuncDetour" method I get vector "foreach" issues and need to modify the code like so:
```
class ThreadManager
		{
		public:
			void SuspendThreads()
			{
				UpdateThreadList(GetCurrentThreadId());
				/*for (ThreadHandle& ThreadInstance : m_SuspendedThreads)
				{
					ThreadInstance.ToggleSuspend(true);
				}*/
				for (int i = 0; i != m_SuspendedThreads.size(); ++i)
				{
					m_SuspendedThreads[i].ToggleSuspend(true);
				}
			}

			void ResumeThreads()
			{
				/*for (ThreadHandle& ThreadInstance : m_SuspendedThreads)
				{
					ThreadInstance.ToggleSuspend(false);
				}*/
				for (int i = 0; i != m_SuspendedThreads.size(); ++i)
				{
					m_SuspendedThreads[i].ToggleSuspend(false);
				}
			}
```

**Comment by stevemk14ebr** [comment] 2017-04-14 23:57
your typedef for the function is wrong on x64 then. You had to modify the foreach because your compiler doesn't support c++11, this is not recommended for polyhook, upgrade to at least vs2015.

**Comment by zezba9000** [comment] 2017-04-14 23:59
I'm using VS 2017 fully up to date.
I get error: "vector iterator not dereferencable" on line "for (ThreadHandle& ThreadInstance : m_SuspendedThreads)" in the "void ResumeThreads()" method

**Comment by zezba9000** [comment] 2017-04-15 00:03
I think this issue happens because the returned value is bigger then 64 bytes. All hooked methods work unless they return more than the register size.

**Comment by stevemk14ebr** [comment] 2017-04-15 00:08
I'm in the process of a full re-write I will be deving on vs2017 so I will investigate foreach problem and avoid it in next release. As for your issue, it is an issue with your typedef, since this is not an issue with polyhook I am going to close this issue. I suggest you debug your target and figure out how it uses the registers and make sure your typedef is appropriate. If you have issues make a thread on unknowncheats.me (after you do research) and the guys there can explain typedefs to you in detail.

**Closed as completed** 2017-04-15 00:09 UTC
Labels: help wanted

**Comment by zezba9000** [comment] 2017-04-15 00:22
**If my typedef was wrong it shouldn't work on x86 then.** Its a standard function ptr typedef.
The code compiles fine in both **VS2015** and **VS2017** (thats NOT the issue). Its NOT a compiler issue, its a runtime issue.

**If I send you $200 via PayPal** and a very simple project illustrating the problem in VS2015 would you be willing to take a look? I'm in a crunch to get it working and calling conventions aren't my specialty.

**Comment by stevemk14ebr** [comment] 2017-04-15 00:39
I am aware the issue is a runtime issue, it is because of your typedef as i said. Different calling conventions exist between x86 and x64, also different optimization can happen. In this case i think return value optimization is occuring, which means instead of returning the struct by making a copy, they function is instead changed to pass a hidden parameter. https://en.wikipedia.org/wiki/Return_value_optimization

Try this for x64 (i added an extra void* and removed static). I can't do more unless i see the disassembly of the function you are hooking, this is a guess as it is
typedef DriverPose_t*(__thiscall *GetPose_Org)(void* HiddenNVORet, ITrackedDeviceServerDriver* thisptr);

DriverPose_t* __fastcall GetPose_Hook(void* HiddenNVORet,ITrackedDeviceServerDriver* thisptr)


I have a donation button on project home page. You can donate if you wish, i will help as much as I can for free, i'm not going to hold you hostage.

**Comment by zezba9000** [comment] 2017-04-15 01:09
Thats super close. "HiddenNVORet" now points to a valid this obj ptr.

This is the method before being hooked:
```
	auto result = shimTrackedDevice->GetPose();
00007FF75FAB43D3  mov         rax,qword ptr [shimTrackedDevice (07FF75FE630A8h)]  
00007FF75FAB43DA  mov         rax,qword ptr [rax]  
00007FF75FAB43DD  lea         rdx,[result]  
00007FF75FAB43E1  mov         rcx,qword ptr [shimTrackedDevice (07FF75FE630A8h)]  
00007FF75FAB43E8  call        qword ptr [rax+28h] 
```

This is the method after being hooked
```
	result = shimTrackedDevice->GetPose();
00007FF60634443F  mov         rax,qword ptr [shimTrackedDevice (07FF6066F30A8h)]  
00007FF606344446  mov         rax,qword ptr [rax]  
00007FF606344449  lea         rdx,[rbp+2D0h]  
00007FF606344450  mov         rcx,qword ptr [shimTrackedDevice (07FF6066F30A8h)]  
00007FF606344457  call        qword ptr [rax+28h]  
00007FF60634445A  lea         rcx,[result]  
00007FF60634445E  mov         rdi,rcx  
00007FF606344461  mov         rsi,rax  
00007FF606344464  mov         ecx,118h  
00007FF606344469  rep movs    byte ptr [rdi],byte ptr [rsi]  
```

When the delete method is call it has the error:
```
HEAP CORRUPTION DETECTED: after Normal block (#163) at 0x000002AA04F157B0.
CRT detected that the application wrote to memory after end of heap buffer.
```
ASM:
```
	delete shimTrackedDevice;
00007FF60634448E  mov         rax,qword ptr [shimTrackedDevice (07FF6066F30A8h)]  
00007FF606344495  mov         qword ptr [rbp+408h],rax  
00007FF60634449C  mov         edx,8  
00007FF6063444A1  mov         rcx,qword ptr [rbp+408h]  
00007FF6063444A8  call        operator delete (07FF60632BDC5h)  
```

Code call overview:
```
static ShimTrackedDevice* shimTrackedDevice = new ShimTrackedDevice();
int main()
{
	cout << "Call before hook..." << endl;
	auto result = shimTrackedDevice->GetPose();

	cout << "Hooking..." << endl;
	HookDriver(shimTrackedDevice, true);

	cout << "Calling Hooked..." << endl;
	result = shimTrackedDevice->GetPose();

	cout << "Deleting..." << endl;
	delete shimTrackedDevice;
	shimTrackedDevice = nullptr;

	cout << "Finished!" << endl;
    return 0;
}
```

**Comment by stevemk14ebr** [comment] 2017-04-15 01:16
Post disassembly of the shimTrackedDevice->GetPose(); where it is called

**Comment by zezba9000** [comment] 2017-04-17 17:41
Sorry for late replay, long weekend.

This is the disassembly for void main that calls the method:
```
--- d:\temp\hooktest\hooktest\hooktest.cpp -------------------------------------
int main()
{
00007FF688AD4380  push        rbp  
00007FF688AD4382  push        rsi  
00007FF688AD4383  push        rdi  
00007FF688AD4384  sub         rsp,440h  
00007FF688AD438B  lea         rbp,[rsp+20h]  
00007FF688AD4390  mov         rdi,rsp  
00007FF688AD4393  mov         ecx,110h  
00007FF688AD4398  mov         eax,0CCCCCCCCh  
00007FF688AD439D  rep stos    dword ptr [rdi]  
00007FF688AD439F  mov         rax,qword ptr [__security_cookie (07FF688E82A58h)]  
00007FF688AD43A6  xor         rax,rbp  
00007FF688AD43A9  mov         qword ptr [rbp+418h],rax  
	cout << "Call before hook..." << endl;
00007FF688AD43B0  lea         rdx,[string "Call before hook..." (07FF688C5BB80h)]  
00007FF688AD43B7  mov         rcx,qword ptr [__imp_std::cout (07FF688E8C218h)]  
00007FF688AD43BE  call        std::operator<<<std::char_traits<char> > (07FF688ABB68Bh)  
00007FF688AD43C3  lea         rdx,[std::endl<char,std::char_traits<char> > (07FF688ABB3D4h)]  
00007FF688AD43CA  mov         rcx,rax  
00007FF688AD43CD  call        qword ptr [__imp_std::basic_ostream<char,std::char_traits<char> >::operator<< (07FF688E8C2B0h)]  
	auto result = shimTrackedDevice->GetPose();
00007FF688AD43D3  mov         rax,qword ptr [shimTrackedDevice (07FF688E830A8h)]  
00007FF688AD43DA  mov         rax,qword ptr [rax]  
00007FF688AD43DD  lea         rdx,[result]  
00007FF688AD43E1  mov         rcx,qword ptr [shimTrackedDevice (07FF688E830A8h)]  
00007FF688AD43E8  call        qword ptr [rax+28h]  

	cout << "Hooking..." << endl;
00007FF688AD43EB  lea         rdx,[string "Hooking..." (07FF688C5BB98h)]  
00007FF688AD43F2  mov         rcx,qword ptr [__imp_std::cout (07FF688E8C218h)]  
00007FF688AD43F9  call        std::operator<<<std::char_traits<char> > (07FF688ABB68Bh)  
00007FF688AD43FE  lea         rdx,[std::endl<char,std::char_traits<char> > (07FF688ABB3D4h)]  
00007FF688AD4405  mov         rcx,rax  
00007FF688AD4408  call        qword ptr [__imp_std::basic_ostream<char,std::char_traits<char> >::operator<< (07FF688E8C2B0h)]  
	HookDriver(shimTrackedDevice, true);
00007FF688AD440E  mov         dl,1  
00007FF688AD4410  mov         rcx,qword ptr [shimTrackedDevice (07FF688E830A8h)]  
00007FF688AD4417  call        HookDriver (07FF688ABBB31h)  

	cout << "Calling Hooked..." << endl;
00007FF688AD441C  lea         rdx,[string "Calling Hooked..." (07FF688C5BBA8h)]  
00007FF688AD4423  mov         rcx,qword ptr [__imp_std::cout (07FF688E8C218h)]  
00007FF688AD442A  call        std::operator<<<std::char_traits<char> > (07FF688ABB68Bh)  
00007FF688AD442F  lea         rdx,[std::endl<char,std::char_traits<char> > (07FF688ABB3D4h)]  

	cout << "Calling Hooked..." << endl;
00007FF688AD4436  mov         rcx,rax  
00007FF688AD4439  call        qword ptr [__imp_std::basic_ostream<char,std::char_traits<char> >::operator<< (07FF688E8C2B0h)]  
	result = shimTrackedDevice->GetPose();
00007FF688AD443F  mov         rax,qword ptr [shimTrackedDevice (07FF688E830A8h)]  
00007FF688AD4446  mov         rax,qword ptr [rax]  
00007FF688AD4449  lea         rdx,[rbp+2D0h]  
00007FF688AD4450  mov         rcx,qword ptr [shimTrackedDevice (07FF688E830A8h)]  
00007FF688AD4457  call        qword ptr [rax+28h]  
00007FF688AD445A  lea         rcx,[result]  
00007FF688AD445E  mov         rdi,rcx  
00007FF688AD4461  mov         rsi,rax  
00007FF688AD4464  mov         ecx,118h  
00007FF688AD4469  rep movs    byte ptr [rdi],byte ptr [rsi]  

	cout << "Deleting..." << endl;
00007FF688AD446B  lea         rdx,[string "Deleting..." (07FF688C5BBC0h)]  
00007FF688AD4472  mov         rcx,qword ptr [__imp_std::cout (07FF688E8C218h)]  
00007FF688AD4479  call        std::operator<<<std::char_traits<char> > (07FF688ABB68Bh)  
00007FF688AD447E  lea         rdx,[std::endl<char,std::char_traits<char> > (07FF688ABB3D4h)]  
00007FF688AD4485  mov         rcx,rax  
00007FF688AD4488  call        qword ptr [__imp_std::basic_ostream<char,std::char_traits<char> >::operator<< (07FF688E8C2B0h)]  
	delete shimTrackedDevice;
00007FF688AD448E  mov         rax,qword ptr [shimTrackedDevice (07FF688E830A8h)]  
00007FF688AD4495  mov         qword ptr [rbp+408h],rax  
00007FF688AD449C  mov         edx,8  
00007FF688AD44A1  mov         rcx,qword ptr [rbp+408h]  
00007FF688AD44A8  call        operator delete (07FF688ABBDC5h)  
	shimTrackedDevice = nullptr;
00007FF688AD44AD  mov         qword ptr [shimTrackedDevice (07FF688E830A8h)],0  

	cout << "Finished!" << endl;
00007FF688AD44B8  lea         rdx,[string "Finished!" (07FF688C5BBD0h)]  
00007FF688AD44BF  mov         rcx,qword ptr [__imp_std::cout (07FF688E8C218h)]  
00007FF688AD44C6  call        std::operator<<<std::char_traits<char> > (07FF688ABB68Bh)  
00007FF688AD44CB  lea         rdx,[std::endl<char,std::char_traits<char> > (07FF688ABB3D4h)]  
00007FF688AD44D2  mov         rcx,rax  
00007FF688AD44D5  call        qword ptr [__imp_std::basic_ostream<char,std::char_traits<char> >::operator<< (07FF688E8C2B0h)]  
    return 0;
00007FF688AD44DB  xor         eax,eax  
}
00007FF688AD44DD  mov         edi,eax  
00007FF688AD44DF  lea         rcx,[rbp-20h]  
00007FF688AD44E3  lea         rdx,[__xt_z+2868h (07FF688C5A430h)]  
00007FF688AD44EA  call        _RTC_CheckStackVars (07FF688ABB749h)  
00007FF688AD44EF  mov         eax,edi  
00007FF688AD44F1  mov         rcx,qword ptr [rbp+418h]  
00007FF688AD44F8  xor         rcx,rbp  
00007FF688AD44FB  call        __security_check_cookie (07FF688ABBFFFh)  
00007FF688AD4500  lea         rsp,[rbp+420h]  
00007FF688AD4507  pop         rdi  
00007FF688AD4508  pop         rsi  
00007FF688AD4509  pop         rbp  
00007FF688AD450A  ret  
--- No source file -------------------------------------------------------------
```

And here it is for the hooked method getting called:
```
--- d:\temp\hooktest\hooktest\hooktest.cpp -------------------------------------
};

// ----------------------------------------------------------
// hooks
// ----------------------------------------------------------
void** trackedDeviceVTable = nullptr;
constexpr int trackedDeviceVTableIndex_GetPose_Index = 5;
typedef DriverPose_t(__thiscall *GetPose_Org)(ITrackedDeviceServerDriver* thisptr);
GetPose_Org GetPose_Ptr = nullptr;

float x = 0;
ITrackedDeviceServerDriver* thisptr__ = nullptr;
DriverPose_t* __fastcall GetPose_Hook(void* HiddenNVORet, ITrackedDeviceServerDriver* thisptr)//, int edx)
{
00007FF688AC9070  mov         qword ptr [rsp+10h],rdx  
00007FF688AC9075  mov         qword ptr [rsp+8],rcx  
00007FF688AC907A  push        rbp  
00007FF688AC907B  push        rsi  
00007FF688AC907C  push        rdi  
00007FF688AC907D  sub         rsp,410h  
00007FF688AC9084  lea         rbp,[rsp+20h]  
00007FF688AC9089  mov         rdi,rsp  
00007FF688AC908C  mov         ecx,104h  
00007FF688AC9091  mov         eax,0CCCCCCCCh  
00007FF688AC9096  rep stos    dword ptr [rdi]  
00007FF688AC9098  mov         rcx,qword ptr [rsp+438h]  
00007FF688AC90A0  mov         rax,qword ptr [__security_cookie (07FF688E82A58h)]  
00007FF688AC90A7  xor         rax,rbp  
00007FF688AC90AA  mov         qword ptr [rbp+3E8h],rax  
	if (thisptr__ == HiddenNVORet) cout << "Valid This Ptr!!!" << endl;
00007FF688AC90B1  mov         rax,qword ptr [HiddenNVORet]  
00007FF688AC90B8  cmp         qword ptr [thisptr__ (07FF688E83028h)],rax  
00007FF688AC90BF  jne         GetPose_Hook+76h (07FF688AC90E6h)  
00007FF688AC90C1  lea         rdx,[string "Valid This Ptr!!!" (07FF688C5BB50h)]  
00007FF688AC90C8  mov         rcx,qword ptr [__imp_std::cout (07FF688E8C218h)]  
00007FF688AC90CF  call        std::operator<<<std::char_traits<char> > (07FF688ABB68Bh)  
00007FF688AC90D4  lea         rdx,[std::endl<char,std::char_traits<char> > (07FF688ABB3D4h)]  
00007FF688AC90DB  mov         rcx,rax  
00007FF688AC90DE  call        qword ptr [__imp_std::basic_ostream<char,std::char_traits<char> >::operator<< (07FF688E8C2B0h)]  
00007FF688AC90E4  jmp         GetPose_Hook+99h (07FF688AC9109h)  
	else cout << "Invalid This Ptr!!!" << endl;
00007FF688AC90E6  lea         rdx,[string "Invalid This Ptr!!!" (07FF688C5BB68h)]  
00007FF688AC90ED  mov         rcx,qword ptr [__imp_std::cout (07FF688E8C218h)]  
00007FF688AC90F4  call        std::operator<<<std::char_traits<char> > (07FF688ABB68Bh)  
00007FF688AC90F9  lea         rdx,[std::endl<char,std::char_traits<char> > (07FF688ABB3D4h)]  
00007FF688AC9100  mov         rcx,rax  
00007FF688AC9103  call        qword ptr [__imp_std::basic_ostream<char,std::char_traits<char> >::operator<< (07FF688E8C2B0h)]  
	return &GetPose_Ptr((ITrackedDeviceServerDriver*)HiddenNVORet);
00007FF688AC9109  mov         rdx,qword ptr [HiddenNVORet]  
00007FF688AC9110  lea         rcx,[rbp+2C8h]  
00007FF688AC9117  call        qword ptr [GetPose_Ptr (07FF688E83018h)]  
00007FF688AC911D  lea         rcx,[rbp+190h]  
00007FF688AC9124  mov         rdi,rcx  
00007FF688AC9127  mov         rsi,rax  
00007FF688AC912A  mov         ecx,118h  
00007FF688AC912F  rep movs    byte ptr [rdi],byte ptr [rsi]  
00007FF688AC9131  lea         rax,[rbp+190h]  
	//return nullptr;
}
00007FF688AC9138  mov         rcx,qword ptr [rbp+3E8h]  
00007FF688AC913F  xor         rcx,rbp  
00007FF688AC9142  call        __security_check_cookie (07FF688ABBFFFh)  
00007FF688AC9147  lea         rsp,[rbp+3F0h]  
00007FF688AC914E  pop         rdi  
00007FF688AC914F  pop         rsi  
00007FF688AC9150  pop         rbp  
00007FF688AC9151  ret  
--- No source file -------------------------------------------------------------
```

**Comment by zezba9000** [comment] 2017-04-17 18:25
Ok you're solution worked, I forgot to change the typedef.

So "typedef DriverPose_t*(__thiscall *GetPose_Org)(void* HiddenNVORet, ITrackedDeviceServerDriver* thisptr);" works!!!

I'll be donating soon, tnx for your help on this! Will have to spend some more time going over why this solution works in asm. Let me know if you would still like disassembly for any of this to help with your API.
